# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
  application:
    name: bootvue
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.seeyourface.bootvue.entity

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true




